### ISSUE TITLE
swiftpackagemanager error on Xcode 14

### ISSUE THREAD

**Issue by cHuMaRi** [dfreniche/SwiftCLITemplate#1]
In case it's of any use to someone...

I had an issue generating the template:
"error: 'swiftpackagemanager': Invalid manifest"

Apparently, after installing Xcode 14 on macOS Monterrey (12.6), Xcode path was incorrect:

I fixed it with the command:
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

Regards!

**Comment by dfreniche** [comment]
Hi @cHuMaRi 

Thanks for reporting. Will test and add that to the README file. Seems like Xcode Command Line Tools were not correctly pointing to the last Xcode installed.

Thanks!

**Comment by dfreniche** [comment]
Improved README giving proper credit 😉
